import type { QuizCategoryCard } from '@/lib/quiz-data/types';

export interface GenericMatcherCatalogItem extends QuizCategoryCard {
  categorySlug: string;
}

export const GENERIC_MATCHER_CATALOG: GenericMatcherCatalogItem[] = [
  {
    category: 'ai-marketing-tools',
    categorySlug: 'ai-marketing-tools',
    title: 'AI Marketing Tools Matcher',
    subtitle: 'Find the marketing tool that fits campaigns, ops, and reporting.',
    description: 'Category matcher',
    cardDescription: 'A scalable matcher for marketing platforms, automation, and campaign workflows.',
    estimatedTime: '70 seconds',
    toolCount: 0,
    icon: 'sparkles',
  },
  {
    category: 'ai-writing-tools',
    categorySlug: 'ai-writing-tools',
    title: 'AI Writing Tools Matcher',
    subtitle: 'Find the writing tool that fits your publishing workflow.',
    description: 'Category matcher',
    cardDescription: 'Use a guided shortlist instead of opening every writing tool one by one.',
    estimatedTime: '60 seconds',
    toolCount: 0,
    icon: 'pen-square',
  },
  {
    category: 'ai-image-tools',
    categorySlug: 'ai-image-tools',
    title: 'AI Image Tools Matcher',
    subtitle: 'Pick the best fit for image generation, editing, and creative work.',
    description: 'Category matcher',
    cardDescription: 'Narrow image tools by workflow, speed, and budget before you compare in detail.',
    estimatedTime: '60 seconds',
    toolCount: 0,
    icon: 'image',
  },
  {
    category: 'ai-video-tools',
    categorySlug: 'ai-video-tools',
    title: 'AI Video Tools Matcher',
    subtitle: 'Choose the right tool for creation, editing, and short-form output.',
    description: 'Category matcher',
    cardDescription: 'Useful when your shortlist spans creation, editing, captioning, and publishing workflows.',
    estimatedTime: '70 seconds',
    toolCount: 0,
    icon: 'captions',
  },
  {
    category: 'ai-subtitle-generators',
    categorySlug: 'ai-subtitle-generators',
    title: 'AI Subtitle Generators Matcher',
    subtitle: 'Choose the best subtitle workflow for creators and teams.',
    description: 'Category matcher',
    cardDescription: 'A category matcher for captioning, subtitles, and short-form video publishing.',
    estimatedTime: '60 seconds',
    toolCount: 0,
    icon: 'captions',
  },
  {
    category: 'seo-tools',
    categorySlug: 'seo-tools',
    title: 'AI SEO Tools Matcher',
    subtitle: 'Find the SEO tool that fits briefs, optimization, and reporting.',
    description: 'Category matcher',
    cardDescription: 'A scalable shortlist path for SEO teams, consultants, and content operators.',
    estimatedTime: '75 seconds',
    toolCount: 0,
    icon: 'search',
  },
  {
    category: 'ai-productivity-tools',
    categorySlug: 'ai-productivity-tools',
    title: 'AI Productivity Tools Matcher',
    subtitle: 'Match the right productivity layer to your team’s workflow.',
    description: 'Category matcher',
    cardDescription: 'Best for teams comparing note-taking, task support, and operational productivity tools.',
    estimatedTime: '60 seconds',
    toolCount: 0,
    icon: 'sparkles',
  },
  {
    category: 'ai-design-tools',
    categorySlug: 'ai-design-tools',
    title: 'AI Design Tools Matcher',
    subtitle: 'Find the design workflow that matches your output and skill level.',
    description: 'Category matcher',
    cardDescription: 'Use this when the shortlist mixes creative tooling, editing, and production support.',
    estimatedTime: '70 seconds',
    toolCount: 0,
    icon: 'image',
  },
  {
    category: 'ai-general-tools',
    categorySlug: 'ai-general-tools',
    title: 'AI General Tools Matcher',
    subtitle: 'Sort broad AI tools into a sharper shortlist faster.',
    description: 'Category matcher',
    cardDescription: 'A good catch-all matcher for general platforms, assistants, and broad AI utilities.',
    estimatedTime: '60 seconds',
    toolCount: 0,
    icon: 'sparkles',
  },
  {
    category: 'ai-chatbots',
    categorySlug: 'ai-chatbots',
    title: 'AI Chatbots Matcher',
    subtitle: 'Choose the right conversational AI workflow for support, sales, or product.',
    description: 'Category matcher',
    cardDescription: 'Built for future chatbot inventory so the category can scale cleanly as tools are published.',
    estimatedTime: '65 seconds',
    toolCount: 0,
    icon: 'sparkles',
  },
  {
    category: 'ai-ui-generators',
    categorySlug: 'ai-ui-generators',
    title: 'AI UI Generators Matcher',
    subtitle: 'Find the right UI generation workflow for product and design teams.',
    description: 'Category matcher',
    cardDescription: 'A scalable matcher for interface-generation tools as the design stack grows.',
    estimatedTime: '65 seconds',
    toolCount: 0,
    icon: 'image',
  },
  {
    category: 'ai-voice-tools',
    categorySlug: 'ai-voice-tools',
    title: 'AI Voice Tools Matcher',
    subtitle: 'Find the best fit for voice generation, cloning, and audio workflows.',
    description: 'Category matcher',
    cardDescription: 'A scalable path for voice and audio tooling as the category grows.',
    estimatedTime: '65 seconds',
    toolCount: 0,
    icon: 'sparkles',
  },
  {
    category: 'text-to-speech',
    categorySlug: 'text-to-speech',
    title: 'Text to Speech Matcher',
    subtitle: 'Match the right voice workflow to narration, content, and product use.',
    description: 'Category matcher',
    cardDescription: 'Useful for voice synthesis, narration, dubbing, and audio production workflows.',
    estimatedTime: '60 seconds',
    toolCount: 0,
    icon: 'sparkles',
  },
  {
    category: 'copywriting',
    categorySlug: 'copywriting',
    title: 'Copywriting Tools Matcher',
    subtitle: 'Choose the copy tool that fits landing pages, ads, and content ops.',
    description: 'Category matcher',
    cardDescription: 'A scalable shortlist path for copywriting tools and campaign-focused writing workflows.',
    estimatedTime: '60 seconds',
    toolCount: 0,
    icon: 'pen-square',
  },
  {
    category: 'avatar-generators',
    categorySlug: 'avatar-generators',
    title: 'Avatar Generators Matcher',
    subtitle: 'Find the avatar workflow that fits branding, creators, and profile assets.',
    description: 'Category matcher',
    cardDescription: 'Useful for avatar, persona, and identity-visual tool categories as more inventory is published.',
    estimatedTime: '55 seconds',
    toolCount: 0,
    icon: 'image',
  },
];

export function getGenericMatcherCard(category: string) {
  return GENERIC_MATCHER_CATALOG.find((item) => item.category === category) ?? null;
}
